# Generated by Django 5.2 on 2025-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cushioning', models.CharField(max_length=50)),
                ('drop_mm', models.FloatField()),
                ('weight_grams', models.IntegerField()),
                ('surface', models.CharField(max_length=50)),
                ('foot_strike', models.CharField(max_length=50)),
                ('pronation_support', models.BooleanField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
